### ISSUE TITLE
Suggestion : Can we make object selection searchable 

### ISSUE THREAD

**Issue by gs-akhan** [ryanbrainard/forceworkbench#651]
Hi, 
The object selection while running query is usually a big one. It has many objects listed and gets cumbersome. So will it be accepted If I make object selection searchable. ? 
I would be more than happy to send PR with this enhancement.
Thanks

**Comment by ryanbrainard** [comment]
Most browsers support typing in the first few characters of the object name, which I have found makes it manageable, but if you want to make it searchable, feel free. You'll probably need to overhaul the whole `printObjectSelection` function.

**Comment by gs-akhan** [comment]
Thanks ryan, one quick question , why do I keep getting "Could not connect to host" while running on https://localhost 

Thanks

**Comment by ryanbrainard** [comment]
try `http` (not `https`) and set the port number.

**Comment by gs-akhan** [comment]
I mean to to say this.
![screen shot 2015-04-11 at 1 22 05 am](https://cloud.githubusercontent.com/assets/5646166/7095579/3c1de9c6-dfe9-11e4-8fd9-db34fc6731dc.png)

**Comment by ryanbrainard** [comment]
Same thing applies. Use http and the port number for localhost
