### ISSUE TITLE
UNKNOWN ERROR: Could not find Terms of Service.

### ISSUE THREAD

**Issue by NittLion78** [ryanbrainard/forceworkbench#652]
Tried logging into Workbench today and was greeted with the following error despite not actually taking any actions upon arrival:

UNKNOWN ERROR: Could not find Terms of Service.
![image](https://cloud.githubusercontent.com/assets/10211553/7097725/fcdddfaa-df9d-11e4-9147-2abe4b00f199.png)

This seems to persist regardless of browser (Chrome & IE) and session/cookie state (tried it in Incognito as well to the same effect).

Any insight?

**Comment by mcescher38** [comment]
same here, started an hour or so ago.

**Comment by ryanbrainard** [comment]
This should be fixed now. Sorry for the inconvenience.
