### ISSUE TITLE
SOAP Error on retrieve or deploy actions

### ISSUE THREAD

**Issue by aj76LEO** [ryanbrainard/forceworkbench#669]
Whenever trying to use Retrieve the below error is returned and the task fails to complete 

UNKNOWN ERROR: SOAP-ERROR: Parsing WSDL: Couldn't load from '/app/workbench/soapclient/sforce.340.metadata.wsdl' : failed to load external entity "/app/workbench/soapclient/sforce.340.metadata.wsdl"

**Comment by worktowindsurf** [comment]
I'm having the same problem today.
It worked fine a couple of weeks ago.
And it works intermittently now.
TLS1.0???

**Comment by ryanbrainard** [comment]
@gmathrubootham Could this be related to https://github.com/gmathrubootham/forceworkbench/commit/84f6dbd89c6d44bd61c129bb54da939b50f08ba3 ?

**Comment by pelangov** [comment]
@aj76LEO  Were you able to find a solution for this issue. I faced a similar issue when I was trying to deploy the changes using workbench.  When I switched to version 33.0, the error didnt occur.

**Comment by dbenn8** [comment]
Hi all,

We were having this problem intermittently (make sense if it's a caching issue), but have uncovered a second issue once we get paste it.  Connecting via lower versions of the metadata API haven't helped.

Once this WSDL issue is cleared, the Retrieve() operation now runs successfully and shows the link to Download a zip file as expected.

However, upon clicking the link, an error is returned stating that the file has been deleted, and warning against refreshing the page.  Fully documented in this new [issue: 672](https://github.com/ryanbrainard/forceworkbench/issues/672)

Is there a size limit on the zip file, I wonder if that could be the issue?

**Comment by worktowindsurf** [comment]
We got over the problem by just refreshing the page <F5>
It looks like the deploy was working, it was the poker checking progress that failed
Though we do have a problem if you try to deploy too much in one go. We have had to split our deployment into 2 files

**Comment by ryanbrainard** [comment]
Just pushed out v34.0.13, which should hopefully fix this.
