### ISSUE TITLE
Unsupported SSL protocol version when using REST Explorer

### ISSUE THREAD

**Issue by davegot13** [ryanbrainard/forceworkbench#671]
When running workbench 34.0.12 on OSX using MAMP, I am getting "Unsupported SSL protocol version" whenever I try to use the REST Explorer. I use a self-signed SSL certificate but that has always worked in the past. This doesn't happen when I use the hosted version of workbench

**Comment by ryanbrainard** [comment]
This probably broke when we upgraded the SSL version to TLS 1.2 for compatibility with future SFDC changes: https://github.com/ryanbrainard/forceworkbench/commit/1f69d3f96340b48eee3db4e29ae5d1625ca8e84d. I would recommend either upgrading MAMP or working with their support. You could also downgrade to  Workbench v34.0.9, but that is probably not great for the log term.
