### ISSUE TITLE
Is this tool capable of running the new Async SOQL queries?

### ISSUE THREAD

**Issue by gcobr** [ryanbrainard/forceworkbench#673]
I would like to know if this tool is capable of running the asynchronous SOQL queries that were introduced in version 16.

See: https://releasenotes.docs.salesforce.com/en-us/winter16/release-notes/rn_general_async_query.htm

If so, how can I tell the tool that a query should run in asynchronous mode?

**Comment by ryanbrainard** [comment]
There is not first-class support, but you should be able to run them in the REST Explorer utility within Workbench under the `/services/data/v35.0/async-queries/` resource.
