### ISSUE TITLE
Workbench not displaying hyperlink on the id field

### ISSUE THREAD

**Issue by MayorovE** [ryanbrainard/forceworkbench#679]
Hello,

We noticed that after a salesforce sandbox org refresh the id field on an account object (for example) does not have a hyperlink where one can choose to view in salesforce etc. The hyperlink does not exist on records created after the org refresh. Can you please tell me if there is a way to get the hyperlink?

I opened a case with SFDC and here is the text:

Hi Eugene,

Thanks for taking my call today. As we discussed, I do see that you cannot access the ID from workbench with the query you provided.
As per the following link: https://developer.salesforce.com/page/Workbench#Query_.26_Search

"Please note that the Workbench is NOT a supported product of or supported by salesforce.com, inc. For support from the Open Source community, please visit this project's pages below:
Project Main Page
Feedback & Discussion
Issues, Bugs, & Feature Requests
Source Code"

Have a look at this link: https://github.com/ryanbrainard/forceworkbench/issues
You may be able to find the issue listed there already or if not, can submit the issue.

I've confirmed that this case can now be closed, however, please be assured that you can re-open the case any time within the next 10 days if you would still like help. Details on how to reopen can be found here: https://help.salesforce.com/apex/HTViewSolution?urlname=Reopening-your-Case-if-needed&language=en_US 

Enjoy the rest of your day!
Sincerely, 

Lisa Mac
Success Agent - Tier 2 - Salesforce 
Office Hours M-F 9am-5pm PT

Thanks
Eugene

**Comment by ryanbrainard** [comment]
I'm guessing it has something to do w/ the ID formats not being recognized. Can you include a screenshot and/or a list of ids that work and ones that don't?

**Comment by MayorovE** [comment]
Hi Ryan,

I attached a screenshot, please let me know if you need anything else. I
can also schedule a remote session if need be, just give me your available
time frame. Thanks for looking into this! I really appreciate it.

Eugene

**Comment by ryanbrainard** [comment]
@MayorovE Please attach the screenshot directly in GitHub (it does not support attachments from email replies)

**Comment by MayorovE** [comment]
Sure, here you go. Thanks!
![workbenchidlink](https://cloud.githubusercontent.com/assets/18177230/14184452/3c07f8e2-f743-11e5-8b18-c9d8661bca08.JPG)

**Comment by ryanbrainard** [comment]
@MayorovE This should now be fixed. Try again and see if it works for you.

**Comment by MayorovE** [comment]
Hi Ryan,

I did see that the links are back. Are you able to tell me what the problem was and how to go about it in the future?

Thanks
Eugene

**Comment by diligent176** [comment]
It was just a little bug.  You can see in the commit history what Ryan changed today:
https://github.com/ryanbrainard/forceworkbench/commit/61e84b9f347b3bd37e44e62fbbeba78ac824c64d

**Comment by CAfromCA** [comment]
@ryanbrainard I think there is still a bug lurking in the addLinksToIds() function.

This is from the [SOAP API Developer Guide](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/field_types.htm#i1435616):

> ID fields in the Salesforce user interface contain 15-character, base-62, case-sensitive strings. Each of the 15 characters can be a numeric digit (0-9), a lowercase letter (a-z), or an uppercase letter (A-Z). Two unique IDs may only be different by a change in case.

I understand that to mean that all 18 characters in an ID-plus-checksum are alphanumeric, with no guarantees that any will be zeros. I think several characters are only _currently_ reliably zeros because total counts of records (and maybe of sandboxes?) aren't high enough yet to roll over into those characters.

If I'm correct, shouldn't the ID-matching regex be `/\b(\w{18})\b/` or maybe (since underscores aren't valid) `/\b([A-Za-z0-9]{18})\b/` ?
