### ISSUE TITLE
Host must match *.salesforce.com

### ISSUE THREAD

**Issue by wnewlin** [ryanbrainard/forceworkbench#682]
Started receiving this error this morning, wondering if there where any changes made and if this is something I can work around. My SF domain is actually a *cloudforce.com 

thanks,

**Comment by ryanbrainard** [comment]
I'm not familiar with the *.cloudforce.com domains. Is there an equivalent *.salesforce.com domain you can use instead?

**Comment by wnewlin** [comment]
No, our org is setup with a branded login page. This is totally bumming me out, I have become very reliant on the workbench tool. Not much runs SOQL queries as well as workbench.

https://developer.salesforce.com/docs/atlas.en-us.packagingGuide.meta/packagingGuide/trialforce_creating_branded_login.htm

**Comment by fmelchor** [comment]
We are also having this issue, we use workbench on a daily basis in development, implementation and support for our customers' orgs. All of our orgs that have a custom url, such as https://fieldfx-2247.cloudforce.com/, can no longer log in to workbench. There is something that was changed that is causing this issue. 
![workbenchscreen1](https://cloud.githubusercontent.com/assets/19615422/15620907/c95648be-2422-11e6-848f-d4ac8a37ba6c.png)

I also opened a ticket with Salesforce, and they say they can not assist.

**Comment by ryanbrainard** [comment]
*.cloudforce.com has been added to the whitelist. Sorry about the breakage.

**Comment by zarizahra** [comment]
Hi @ryanbrainard I think we're facing a very similar issue - described here:

https://salesforce.stackexchange.com/questions/218881/oauth2-0-returns-unreachable-instance-url
https://developer.salesforce.com/forums?id=9060G0000005ccxQAA

Would you be able to shed any light on it? We're at a loss :(
