### ISSUE TITLE
Workbench still pointing to version 39.0 instead of 40.0.

### ISSUE THREAD

**Issue by suresh83kumar** [ryanbrainard/forceworkbench#704]
Workbench still pointing to version 39.0 instead of 40.0. Can you fix it?

**Comment by YBalakrishna** [comment]
Hi Team,
Workbench still pointing to version 39.0 instead of 40.0. Can you please fix it as soon as possible.
I am not able to Test Post and Get methods. If version will be updated to 40.0, it will help me a lot.

**Comment by ryanbrainard** [comment]
v40 is available now.
