### ISSUE TITLE
Not loading today

### ISSUE THREAD

**Issue by milan-j** [ryanbrainard/forceworkbench#708]
After I go to https://workbench.developerforce.com/ I get this message:

Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by AlphaCharlieBravo** [comment]
Same here, it's been down for a couple of hours now.

**Comment by milan-j** [comment]
It's OK now.

**Comment by cgorshing** [comment]
Duplicate of #710
