### ISSUE TITLE
Error: Salesforce session is invalid or has expired

### ISSUE THREAD

**Issue by fcathala** [ryanbrainard/forceworkbench#709]
I successfully connected to the Workbench today (https://workbench.developerforce.com/login.php) side by side with a Salesforce UI session but after a couple of "_Login-As-User_" back and forth I was thrown out of Workbench (while still connected on the UI). 

I now receive the following error on multiple browsers including incognito mode:

> An error has occurred and you have been logged out:
> Your Salesforce session is invalid or has expired. Please login again.

![image](https://user-images.githubusercontent.com/349381/29240597-5587727e-7f60-11e7-85d2-f5c92826b41a.png)

I have cleared the "_Oauth_" sessions in **Session Management** and tried again but didn't work...

**Comment by andrew-chiz-muzychuk** [comment]
I've been having this error for a few months.

**Comment by aericfr** [comment]
Unchek "Lock sessions to the IP address from which they originated" in setup / security Controls / Session Setting in your org.
