### ISSUE TITLE
workbench.developerforce.com SSL Certificate is expired (14-Aug-2017)

### ISSUE THREAD

**Issue by bmaletz** [ryanbrainard/forceworkbench#710]
When trying to open https://workbench.developerforce.com/login.php today (14-Aug-2017), received error; NET::ERR_CERT_DATE_INVALID

**Comment by ryanbrainard** [comment]
Thanks for reporting this. I have started the process of updating the cert, but it will take some time to get things back online. Sorry for the inconvenience.

**Comment by anandsecured** [comment]
Hi Ryan,
Any update on when Workbench will be up and running. We have a dependency to use Workbench to complete a milestone. Appreciate your response.

**Comment by josvervoorn** [comment]
Any new on this. In the EU region workbench still, can't be reached.

**Comment by ryanbrainard** [comment]
No update at this time. Please do not depend on Workbench. There is no SLA and is not supported. Running it locally or on Heroku is always an option. Sorry for the inconvenience.

**Comment by dummyuser82** [comment]
Not sure but what do you mean that it is not supported. If that's the case could you explain the other better options? Apex data loader is not a good option since it is not Agile enough to build relational queries

**Comment by melanie-o2ebrands** [comment]
Any update on the progress of fixing the certificate issue?

**Comment by ashugoyal81** [comment]
Hi Ryan,

When can we expect the issue to be resolved?

**Comment by deckblad** [comment]
@dummyuser82 Workbench is a 3rd party app offered solely by Ryan. It is not a Salesforce product and thus not supported by Salesforce. It's not a production tool per se. It's a developer tool.

Ryan, thanks for all your hard work. PPL like you and Joe Ferraro (MavensMate) make SF dev tolerable :)

**Comment by jasonkrice** [comment]
Totally second the sentiment from @deckblad -- thank you for your hard work and contributions to the community, especially givens the at-times thankless nature of it. You are appreciated!

**Comment by snugsfbay** [comment]
If it is not supported, why are their Salesforce Certification questions on it?

**Comment by jscottjgit** [comment]
I third the sentiment from @deckblad (and second the sentiment from @jasonkrice)

Thank you for all your hard work!  I use this tool every day of my life!

**Comment by bmaletz** [comment]
@ryanbrainard many thanks for your swift action, and more ever for your generous and invaluable contribution to SDFC community. It is truly astonishing that one person can develop and support such comprehensive tool. Just like @deckblad, I also use it everyday of my life.

**Comment by senhoreto** [comment]
@ryanbrainard Thank you for your Help.

**Comment by wmccullough-opengate** [comment]
@ryanbrainard Ryan....Thank you for your contribution to support a public instance of Workbench.  I had no idea that it wasn't a tool supported by Salesforce!  I use Workbench almost everyday.  It has made my work with Salesforce much easier.  Best Regards!  Bill

**Comment by josvervoorn** [comment]
Seems like the outage is a good thing for the common understanding of who dedicates their time and efforts to this valuable tool. I use this tool on a daily basis and @ryanbrainard maintaining and support workbench should not be taken for granted. I know now that I should not rely on this tool but it's with miles distance the best irreplaceable 'swiss-army' tool I know. @ryanbrainard all the best and I hope you can manage to resolve soon.

**Comment by saihanuman** [comment]
@ryanbrainard Thankyou for your greatness, Can you please let us know when will it be back on track?

**Comment by Jerrodinc** [comment]
You mention running it locally or on Heroku.  How do I learn more about that?  Also, thanks for this tool, it's a true lifesaver.

**Comment by Rick-Letters** [comment]
@Jerrodinc I found information about it here:
https://developer.salesforce.com/page/Workbench#Installation

**Comment by sparkle012** [comment]
Hi Ryan, thanks for your good work. but can you please help and fix this issue for us. this tool is a lifeline for us now. please let us know when this issue is fixed.

**Comment by manhesoft** [comment]
@Rick-Letters thanks, but it's not work, (i did install on my localhost, and Heroku). is it work for you?

**Comment by ssimmons99** [comment]
Hopefully, you can get this fixed.  Workbench is far and away the best tool for working with Salesforce data.  The developer console is inadequate to the task.
Salesforce needs to support this tool.. Thanks to Ryan for developing this.
Is there anything we can do to help the cause?  Please let me know.

**Comment by Rick-Letters** [comment]
@manhesoft Did you grab an SSO add-on for your browser? I had to add one in pointed at my localhost before it would work, although you'll have to take additional steps to secure your connection once it is up and running.

**Comment by manhesoft** [comment]
https://youtu.be/ibUXgd-nr7I watch this, but it shows me  an error: 

> LOGIN_MUST_USE_SECURITY_TOKEN: Invalid username, password, security token; or user locked out. Are you at a new location? When accessing Salesforce--either via a desktop client or the API--from outside of your company’s trusted networks, you must add a security token to your password to log in. To get your new security token, log in to Salesforce. From your personal settings, enter Reset My Security Token in the Quick Find box, then select Reset My Security Token.

can you help us, how to configure it?, where can i add  my security token?

**Comment by dcinzona** [comment]
Looks like DNS is no longer registered for workbench.
```shell
$ nslookup workbench.developerforce.com
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find workbench.developerforce.com: NXDOMAIN
```

**Comment by Steve-MTH** [comment]
@ryanbrainard Thank you for all your efforts.

**Comment by MenachemShanowitz** [comment]
There is no easy to use tool currently available comparable to workbench. Please do what you can to fix this. Thanks! @ryanbrainard

**Comment by mikedual** [comment]
@ryanbrainard thanks for all your efforts towards Workbench!

I have been able to copy the code into a personal app in Heroku to leverage Workbench until this is resolved.  Others with dependencies should check into these workarounds!

**Comment by diligent176** [comment]
FYI - I've never used Heroku before, but yesterday I signed up for a free account and had my own instance of workbench running in just a few easy clicks.  (Wish I didn't have to, but I have to say it was super easy to get going...)

On the other hand - it still amazes me that Salesforce is unwilling to create and support a tool like this.  It's an absolutely critical tool on the Salesforce admins toolbelt.  Any small outage of workbench is usually a huge inconvenience.

Thanks Ryan for doing all this work!  I do wish Salesforce would step up to the plate and actually make an official supported tool out of this.  Keep it community driven, but also reliable.

**Comment by manhesoft** [comment]
Hi @diligent176 do you have a tutorial about it? how can i configure my salesforce account,
did i try (Heroku and localhost) but no work
 thanks a lot.

**Comment by diligent176** [comment]
It was pretty much two steps:
  1) Go to Heroku and sign up
  2) Click the button "Deploy to Heroku" from the Github page:  https://github.com/ryanbrainard/forceworkbench

A few clicks later it was running on Heroku.
The oAuth doesn't work quite a smoothly as I'm used to, but I got logged in and ran my queries.

**Comment by ssimmons99** [comment]
Thanks!! I'm in

**Comment by jscottjgit** [comment]
Dear Salesforce.  Please make this an officially supported app.   Pay Ryan
am obscene amount of money for it so he can retire and build some more cool
stuff in his spare time.

**Comment by ssimmons99** [comment]
Totally agree with jscottjgit
We can't live without it

**Comment by Sarat-REISys** [comment]
Salesforce developer cannot imagine a workday without workbench. Salesforce please support Ryan.

**Comment by magesk** [comment]
I used Salesforce Workbench every day. Great Tool. Hoping there would be a resolution soon.

**Comment by jasonkrice** [comment]
The solution @diligent176 gives above is super easy. If you absolutely *must* have access to workbench right now, this is your solution and it is only about 5 minutes away:

> diligent176 commented 3 hours ago
> 
> It was pretty much two steps:
> 
> 1. Go to Heroku and sign up
> 2. Click the button "Deploy to Heroku" from the Github page: https://github.com/ryanbrainard/forceworkbench
> 
> A few clicks later it was running on Heroku.
> The oAuth doesn't work quite a smoothly as I'm used to, but I got logged in and ran my queries.

**Comment by Jntshumaker** [comment]
Thank you @diligent176 for the quick and easy Heroku approach, a great alternative as I have observed workbench issues in the past where a local/heroku version would have assisted.

**Comment by mcrdjr** [comment]
I was trying to use it today and found these posts about the DNS issue. I decided to download and install the product on my Mac. After a little trial and error (some TLS stuff) I was able to get it running. Sweet. Thanks ryanbrainard !

**Comment by tubacatak** [comment]
@manhesoft I have the same issue with you :(

LOGIN_MUST_USE_SECURITY_TOKEN: Invalid username, password, security token; or user locked out. Are you at a new location? When accessing Salesforce--either via a desktop client or the API--from outside of your company’s trusted networks, you must add a security token to your password to log in. To get your new security token, log in to Salesforce. From your personal settings, enter Reset My Security Token in the Quick Find box, then select Reset My Security Token.

**Comment by JiriU** [comment]
@ryanbrainard, you're the savior of not only Devs, but Admins too... I have used workbench to perform millions of update/insert operations. No idea how I'd be able to do that without your tool.

**Comment by Jntshumaker** [comment]
@manhesoft @tubacatak Your token can be reset/found in Salesforce by doing the following:

Click your username in the upper left, search for "Reset My Security Token" on the left.  This token is added to the end of your password when logging into workbench.  This process worked for me.

**Comment by Jntshumaker** [comment]
@diligent176 @ryanbrainard 

Would either of you be able to provide guidance on how Redis To Go is setup in Heroku.  Larger queries are timing out faster than normal, with the understanding that I always saw timeouts but it appears my Heroku configuration may be incomplete.  

Based on what I'm reading I am assuming I would need to upgrade my Heroku subscription but would like to confirm as the help documents are not quite giving me what I need to understand this issue.

**Comment by manhesoft** [comment]
@Jntshumaker  Thanks a lot, do not restart my token, just add the token at the end of my passwod and it worked (I did it yesterday), And I was going to write it to help,  thank you very much, because your help works 100% recommended.

**Comment by Suie1** [comment]
So thankful for the Heroku option! (and for Workbench as an awesome tool)

**Comment by dcinzona** [comment]
Obviously, thank you @ryanbrainard for having created and supported the tool!
Regarding:
>  Please do not depend on Workbench. There is no SLA and is not supported. Running it locally or on Heroku is always an option. Sorry for the inconvenience.

If Workbench is not an official Salesforce tool and has no SLA, then IMHO, it should not be required in any trailhead modules nor should it be under the Salesforce developerforce.com domain.

For example: 
-
 https://trailhead.salesforce.com/modules/platform_events_basics/units/platform_events_define_publish
- https://trailhead.salesforce.com/modules/event_monitoring/units/event_monitoring_query
- https://trailhead.salesforce.com/modules/apex_integration_services/units/apex_integration_webservices

I'm sure there's more, but you get the gist.
Salesforce should either adopt this tool and support it in-house, or update the training modules to not require it.

**Comment by netwitt** [comment]
Thanks for the info.  I got Workbench working on my local machine!  It's a godsend.  Thanks for all the work you do in maintaining Workbench!

**Comment by ryanbrainard** [comment]
Workbench is back online. Sorry for the outage and the long delay getting it back online. It required a few people behind the scenes and took some time to get things coordinated. As has been mentioned a few times on this thread, Workbench is not a supported tool (see https://workbench.developerforce.com/terms.php for it's status), so unfortunately there is no SLA when issues like this occur. Thank you to everyone to offered their gratitude for the service.

**Comment by bmaletz** [comment]
Tremendous thanks @ryanbrainard for your invaluable contribution to SFDC community.

**Comment by chau-cloudkinetix** [comment]
Hi @ryanbrainard 
The site is back, but connection is intermittent.Can you please further check.
Thanks so much for the tool.

**Comment by Caroline-wan** [comment]
Hello @ryanbrainard,

Workbench is back but we encounter some connection problems. 
Can you please check

Thank you so much for your help

**Comment by ruchanb** [comment]
![image](https://user-images.githubusercontent.com/11032047/29412678-792da64a-8379-11e7-8434-ff3250ff08a3.png)
I don't think its working yet.

**Comment by Jntshumaker** [comment]
@ryanbrainard Thank you for the prompt action.

**Comment by rajaraodv** [comment]
Seems like it's still having issues

**Comment by Sarat-REISys** [comment]
Workbench is an open souce app available on Git hub we can run the application on Heroku or run on your server. 
Steps to deploy on Heroku.
1. Create Heroku account (if you don't have one)
2. Go to https://github.com/ryanbrainard/forceworkbench
3. Click on Deploy to Heroku
4. Choose an appname
5. Click Deploy. 
6. That simple it is.

**Comment by netwitt** [comment]
I used the directions provided by Rick-Letters using this site https://developer.salesforce.com/page/Workbench#Installation and it work great from my local machine.  Was super easy to install - instructions were spot on.

**Comment by john-brock** [comment]
Please consider up-voting https://success.salesforce.com/ideaView?id=0873A0000003UWrQAM to help advocate for Workbench becoming a supported Salesforce tool.

**Comment by dcinzona** [comment]
👍  up-voted.  I agree, this would be a huge improvement.
