### ISSUE TITLE
"This site can't be reached"

### ISSUE THREAD

**Issue by aovri** [ryanbrainard/forceworkbench#711]
After going to https://workbench.developerforce.com/, Chrome displays the following error message: "This
site can't be reached".

**Comment by ryanbrainard** [comment]
See https://github.com/ryanbrainard/forceworkbench/issues/710. Same root cause

**Comment by aovri** [comment]
Cool, thanks!

**Comment by ryanbrainard** [comment]
Workbench is back online. Sorry for the outage and the long delay getting it back online. It required a few people behind the scenes and took some time to get things coordinated. As has been mentioned a few times on this thread, Workbench is not a supported tool (see https://workbench.developerforce.com/terms.php for it's status), so unfortunately there is no SLA when issues like this occur. Thank you to everyone to offered their gratitude for the service.

**Comment by aovri** [comment]
@ryanbrainard thanks so much. Our team is super happy to get it back! 👍 👍 👍

**Comment by josvervoorn** [comment]
Thanks @ryanbrainard I will keep my Heroku based workbench as backup and cherish yours.

**Comment by john-brock** [comment]
Please consider up-voting https://success.salesforce.com/ideaView?id=0873A0000003UWrQAM to help advocate for Workbench becoming a supported Salesforce tool.
