### ISSUE TITLE
Not Loading / slow

### ISSUE THREAD

**Issue by Stragis** [ryanbrainard/forceworkbench#718]
Hi Folks, workbench seems super slow today. I'm getting application timeouts and unresponsive soql queries
![image](https://user-images.githubusercontent.com/834519/29847589-4c5ef98c-8cd1-11e7-99bf-077bed4800ab.png)

**Comment by dbruce94117** [comment]
I'm having similar but maybe unrelated issues today, October 4th. I've been regularly (but inconsistently getting this error logging in and after getting in, with any query request:
![workbencherror](https://user-images.githubusercontent.com/16005082/31192576-7b512f76-a8f6-11e7-9780-54ef67c6eb0c.PNG)

**Comment by skuruganti** [comment]
I am having some issues with workbench today too, just tried to pull Id from Account in a dev org I have that has relatively small number of accounts and even that is timing out. 

I am glad to see it isn't just me, I was originally getting the error while trying to set up a job and thought I did something wrong. It appears workbench is just having some issues today...

**Comment by skuruganti** [comment]
Update on this... it appears the jobs I opened via workbench are in my org, so the request is going through, I am just not getting the response in workbench.

**Comment by ryanbrainard** [comment]
I just bounced the servers and it seems to be ok now.
